#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-
from logging import getLogger,ERROR
getLogger('scapy.runtime').setLevel(ERROR)
import argparse
import sys
from PyQt5 import QtGui,QtCore
from core.main import PumpkinShell
from core.utility.printer import banner, setcolor
from core.packets.dhcpserver import IpAddressClass
from core.utility.collection import SettingsINI
import core.utility.constants as C

_author  = ('{}'.format(setcolor('@mh4x0f',color='yellow')))
_version = setcolor('0.1',color='yellow')
__codename__ = setcolor('sab1no',color='red')
banner()

if __name__ == '__main__':
    app = QtCore.QCoreApplication(sys.argv)
    conf       = SettingsINI(C.CONFIG_INI)
    ifacedefault = conf.get('accesspoint','interfaceAP')
    session_default = conf.get('accesspoint','current_session')
    parser = argparse.ArgumentParser(description="WiFi-Pumpkin - pure line-oriented command")
    parser.add_argument('-i',  dest='interface',help='set interface for create AP',default=ifacedefault)
    parser.add_argument('-s',  dest='session',help='set session for continue attack',default=session_default)
    parser.add_argument('-p', '--pulp', dest='pulp',help='interactive sessions can be scripted with .pulp file',default='')
    parser.add_argument('-x', '--xpulp', dest='xpulp',help='interactive sessions can be string with ";" as the separator',default='')
    parser.add_argument('-v','--version', action='version', dest='version',version='%(prog)s v{}'.format(_version))
    print('Author: {} P0cL4bs Team'.format(_author))
    print('Version: {} dev'.format(_version))
    print('Codename: {}'.format(__codename__))
    prompt = PumpkinShell(parser.parse_args())
    prompt.cmdloop('Starting prompt...')
    sys.exit(app.exec_())
