#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-
from logging import getLogger,ERROR
getLogger('scapy.runtime').setLevel(ERROR)
import argparse
import sys
from PyQt4 import QtGui
from core.main import FrameworkBash
from core.utility.printer import banner, setcolor
from core.packets.dhcpserver import IpAddressClass

_author  = ('{}'.format(setcolor('@mh4x0f',color='yellow')))
_version = setcolor('0.1',color='yellow')
banner()
if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    parser = argparse.ArgumentParser(description="WiFi-Pumpkin - pure line-oriented command")
    parser.add_argument('-i',  dest='interface',help='set interface for create AP',default=None)
    parser.add_argument('-s',  dest='session',type=int,help='set session for continue attack',default=None)
    parser.add_argument('-v','--version', action='version', dest='version',version='%(prog)s v{}'.format(_version))
    prompt = FrameworkBash(parser.parse_args())
    print('Author: {} P0cL4bs Team'.format(_author))
    print('Version: {} dev'.format(_version))
    prompt.cmdloop('Starting prompt...')
    sys.exit(app.exec_())
